version: 2.1
     
orbs:
  kubernetes: circleci/kubernetes@0.11.2
  aws-eks: circleci/aws-eks@1.0.3
  
jobs:
  Lint:
    docker:
      - image: ubuntu
    steps:
      - checkout
      - run:
          name: install Dependencies
          command: |
            apt-get update
            apt-get install tidy -y
            apt-get install wget -y
            wget -O ./hadolint https://github.com/hadolint/hadolint/releases/download/v1.22.1/hadolint-Linux-x86_64
            chmod +x hadolint
            mv hadolint /bin/hadolint
      - run:
          name: Lint HTML
          command: |
            tidy -q -e *.html
      - run:
          name: Hadolint Dockerfile
          command: |
            hadolint -v
            hadolint --ignore DL3006 Dockerfile

workflows:
  default:
    jobs:
      - Lint
